added library code
arcslaboratory/ue5env pull request #1
Opened 2022-08-12 20:47 UTC by Simon-Heck

2022-08-13 20:51 UTC, anthonyjclark requested changes

2022-08-13 20:51 UTC, anthonyjclark commented on README copy.md
> +# Scripts for running unrealCV and fastAI with UE5
What is this file?

2022-08-13 20:51 UTC, anthonyjclark commented on setup.py
> +setup(name="ue5env",version="0.1",description="wrapper for unreal engine using unrealcv",author="Simon Heck",license="MIT",packages=["ue5env"],zip_safe=False)
This file should be hit with a code formatter.

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +#!/usr/bin/env python
Remove this. This file is not intended to be executed as a script.

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +import shutil
Prefer `pathlib` to `shutil`

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +        ue5.connect(5)
```suggestion
        ue5.connect(timeout=5)
```

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +            exit(0)
Raise an exception instead of exiting.

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +        return self.connected
Should this be:
```suggestion
        return self.ue5.isconnected()
```

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +    def getCameraLocation(self, cameraID: float) -> tuple[float, float, float]:
Should camera id be a float or an int? Also, should we default it to `0`?

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +        return (float(x), float(y), float(z))
```suggestion
        return float(x), float(y), float(z)
```

2022-08-13 20:51 UTC, anthonyjclark commented on ue5env/__init__.py
> +    def left(self, degreeRot: float, cameraNum: int) -> None:
How is `cameraNum` different from `cameraID`?

2022-08-15 18:15 UTC, Simon-Heck commented on ue5env/__init__.py
> +import shutil
Marked with a @TODO. Not sure where unrealCV saves images when working with the remote server and this method is not needed until datacollection starts

2023-01-30 21:05 UTC, closed without merging